---
- name: Install Nginx
  hosts: all
  var: 
    packages:
      - name: nginx
        required: True
      - name: mysql
        required: True
      - name: apache
        required: True
        
  tasks:
  - name: Install "{{ item.name  }}" on Server
    apt:
      name: "{{ item.name  }}"
      state: present
    when: item.required == True
    loop: "{{ packages }}"
