---
- name: Install Nginx
  hosts: all
  tasks:
  - name: checking http status
    register: result
    
  - name: Email alert when service down
    mail:
      to: quandominh@gmail.com
      subject: Service alert
      body: HTTP service down
      when: result.stdout.find("down") != -1